version: "3.9"

services:
  db:
    image: postgres:15
    container_name: eshop-db-1
    environment:
      - POSTGRES_DB=my_project
      - POSTGRES_USER=eshop_user
      - POSTGRES_PASSWORD=MyNewPass123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: eshop-backend-1
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      # ИСПРАВЛЕНО: данные теперь совпадают с блоком db
      - DATABASE_URL=postgres://eshop_user:MyNewPass123@db:5432/my_project

  frontend:
    build: ./frontend
    container_name: eshop-frontend-1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # ДОБАВЛЕНО: чтобы host.docker.internal точно работал в Windows
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: