version: "3.9"

services:
  db:
    image: postgres:15
    container_name: eshop-db-1
    environment:
      - POSTGRES_DB=my_project
      - POSTGRES_USER=eshop_user
      - POSTGRES_PASSWORD=MyNewPass123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: eshop-backend-1
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://eshop_user:MyNewPass123@db:5432/my_project

  frontend:
    build: ./frontend
    container_name: eshop-frontend-1
    ports:
      - "3000:3000"
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
    develop:
      watch:
        - path: ./frontend/app
          action: sync
          target: /app/app
        - path: ./frontend/components
          action: sync
          target: /app/components
        - path: ./frontend/public
          action: sync
          target: /app/public
        - path: ./frontend/package.json
          action: rebuild
    working_dir: /app

volumes:
  postgres_data:
