# Generated by Django 6.0.3 on 2026-04-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_code',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
