# Generated by Django 6.0.2 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_productvariant_color_code"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)),
                name="product_variant_price_non_negative",
            ),
        ),
    ]
